### ISSUE TITLE
simple select query runs into Module Failure issue

### ISSUE THREAD

**Issue by woreis** [redhat-sap/rh_operations#88]
Hi,
I just wanted to test sap_hdbsql.py and immediately run into an issue.
My playbook looks like this:
---

- hosts: '{{ ho | default([]) }}'

  tasks:
  - name: Simple select query
    become: true
    become_user: idhadm
    become_flags: '-i'
    community.sap_libs.sap_hdbsql:
      sid: "IDH"
      database: "SYSTEMDB"
      instance: "00"
      userstore: true
      user: "SYS_SYSTEMDB"
      host: "some.host:30013"
      query: select user_name from users

When I run this, I get the error:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named '_struct'
fatal: [vintdevhdb001.fdz.internal]: FAILED! => {"changed": false, "module_stderr": "Shared connection to som.host closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/var/tmp/ansible-tmp-1725457957.175195-2959474-12846379217444/AnsiballZ_sap_hdbsql.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/var/tmp/ansible-tmp-1725457957.175195-2959474-12846379217444/AnsiballZ_sap_hdbsql.py\", line 24, in _ansiballz_main\r\n    import base64\r\n  File \"/usr/sap/IDH/HDB00/exe/Python3/lib/python3.8/base64.py\", line 10, in <module>\r\n    import struct\r\n  File \"/usr/sap/IDH/HDB00/exe/Python3/lib/python3.8/struct.py\", line 13, in <module>\r\n    from _struct import *\r\nModuleNotFoundError: No module named '_struct'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
But of course the struct.py file can be found on the target system:
[root@some.host ~]# ls -l /usr/sap/IDH/HDB00/exe/Python3/lib/python3.8/struct.py
-r--r--r--. 1 idhadm sapsys 257 Jul 11 22:49 /usr/sap/IDH/HDB00/exe/Python3/lib/python3.8/struct.py
Any idea, what could cause this problem ?
Help would be appreciated, 
Thanks, Wolfgang

**Comment by kksat** [comment]
I believe this is not related to sap.sap_operations collection, but rather to community.sap_libs collection.

Closing
